### ISSUE TITLE
fiber_use_ucontext might need defining in the RFC

### ISSUE THREAD

**Issue by Danack** [trowski/fiber-rfc#3]
I have no idea what it is, but I can see it in the m4 file.

Or it might be a detail that isn't mentioned.

**Comment by trowski** [comment]
Implementation detail. Fibers are implemented using assembly, ucontext, or winfib (windows fibers). I'm not sure how much specific detail this needs in the RFC other than to say fibers should work on any modern platform.

**Comment by Danack** [comment]
Cool, it's a detail then. But can you please add a comment to the m4 file before they are defined - aka here - https://github.com/amphp/ext-fiber/blob/master/config.m4#L13-L14

It's probably only discoverable by people who open the m4 file, and both of them would appreciate a comment there.

**Comment by trowski** [comment]
Now mentioned briefly in the RFC, though as an implementation detail, like WinFiber. ucontext was deprecated in Posix 6 and removed in 7, so I'm not sure it should even be supported. A technical detail to work out, but probably not important to the API proposal.
