### ISSUE TITLE
Boost needs mentioning probably.

### ISSUE THREAD

**Issue by Danack** [trowski/fiber-rfc#4]
both what it is, and that the license makes it usable in PHP

**Comment by Danack** [comment]
I wrote some words, seem good?

> The Fiber class would be implemented internally to PHP using the [Boost Fiber](https://www.boost.org/doc/libs/1_67_0/libs/fiber/doc/html/index.html) library. That library is distributed as source code, under the [Boost license](https://www.boost.org/LICENSE_1_0.txt] which allows it to be distributed with PHP.

**Comment by trowski** [comment]
Done.
