### ISSUE TITLE
Needs comparison to previous RFC

### ISSUE THREAD

**Issue by Danack** [trowski/fiber-rfc#5]
https://wiki.php.net/rfc/fiber

"They do however lack support for anything that involves internal function calls (3) including opcode handlers (4, e.g. foreach loop)." 

and mention platforms. And say why there seems to be small amounts of code change.

**Comment by trowski** [comment]
Yes, the prior attempts all lacked support for swapping the C stack, which is a deal-breaker IMO. I can mention this, perhaps in a to-be-added performance section about needing to also swap stack pointers.

**Comment by trowski** [comment]
Done.
