### ISSUE TITLE
Why no throw into Fiber.

### ISSUE THREAD

**Issue by Danack** [trowski/fiber-rfc#6]
Looking at the previous RFC, it looks like users could throw an exception into the fiber, which sounds like a useful thing to be able to do, to allow code to clean up itself before exiting.

Is there a reason to exclude that, other than might not be needed?

**Comment by trowski** [comment]
Seems you're inferring that this implementation cannot throw into fibers, but that's not the case. This may have been unclear with the awaitable API (awaitables could be failed, which would throw), but the new API makes it clear with `Continuation::throw()`.
